# Generated by Django 4.1.5 on 2023-10-06 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(default='Animal', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='sighting',
            name='animalType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.animal'),
        ),
    ]
